server:
  port: 8667

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8567/eureka/
word:
  dicPath: '/data/seg/dic.txt'
  stopWordsPath: '/data/seg/stopwords.txt'
  bigRamPath: 'classpath: bigram.txt'
  testSegWord: '测试'
  voiceTemp: 'voice_temp'
  suffixName: '.wav'